# Don't print a new line at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

prompt_order = [
    "directory",
    "git_branch",
    "git_status",
    "line_break",
    "time",
    "character",
]

[package]
disabled = true

[nodejs]
disabled = true

[git_branch]
symbol = ""

[time]
disabled = false
format = "%T"
